# The  minus in YAML this indicates a list item. the playbook contains a list of plays,
# with each play being a dictionary

-

  # Hosts: lists of target hosts that we'll run playbooks on

  hosts: all
  user: docker
  gather_facts: False
  become: True

  tasks:
    - name: copy bash script to all servers
      copy:
        src: os_release.sh
        dest: /tmp/os_realese.sh
        mode: 01777

    - name: run script on the servers
      script: os_release.sh
      args:
        chdir: /tmp
      register: printout
  # Vars: variables that apply to the play on all target systems
  # Tasks: list of tasks that will be executed  within play, including pre and post tasks
  # Handlers: list of handlers (notification tasks) that are executed with `notify` keyword from `tasks`
 # Roles: list of roles (dedicated tasks ) to be imported  into the play
 # Note: not all are required to be used in single playbook

...

